### ISSUE TITLE
Add isFinalIteration() method in Policy

### ISSUE THREAD

**Issue by Fithos** [renaissance-benchmarks/renaissance#143]
When performing analyses, it may be useful to know when the benchmark is executing the final iteration, (e.g., to consider it a sort of "steady-state"). Currently, it seems that the `Plugin` and `Policy` classes do not offer a method such as `isFinalIteration()` to know when this is the case. It may be useful to add it.

**Comment by axel22** [comment]
It seems that for some policies it might be hard to know this - for example, how would you implement this in the fixed-time policy?

**Comment by lbulej** [comment]
Could you provide an example use case?

I plan for `Policy` to basically only have 2 ethods. One to determine whether to keep executing the benchmark's measured operation/repetition and one that notifies the policy that the measured operation/repetition has completed (and how long it took). This should allow a fixed-time policy to keep track of net benchmark execution time without polluting it  with execution time spent in plugin hooks.

A plugin can be notified before/after each execution of a measured operation/repetition and before/after benchmark (i.e. before the first and after the last execution of a measured operation/repetition), and thus should be able to keep track of the overall execution.

BTW, I'd suggest to discuss API requirements within issue #81 so that we can keep track of such requirements.

**Comment by Fithos** [comment]
I suggested this addition because in some dynamic analyses we may want to consider all iterations apart from the last as "warm-up", avoiding to collect metrics during such iterations. Without a `isFinalMethod()`, we would need to collect metrics for all the iterations (which, depending on the analysis, may generated large traces) and then filter out metrics not collected during the last iteration. 

If this addition is in contrast to the (planned) design of the `Policy` class, then never mind. It does not prevent to execute analyses anyways :)

**Comment by axel22** [comment]
@rosa-andrea Then I would propose to:

1) Have a method such as `isWarmUpIteration`, that tells you if something is a warm-up iteration or not.
2) Implement it to: in fixed-time policy to return the obvious, in fixed-iterations policy to return true for all iterations but the last.
3) If you want constant-time warmup, and one extra measurement iteration (note: fixed-time does constant time warmup and constant time measurement runs), then implement a 3rd policy that does that.

**Comment by Fithos** [comment]
> @rosa-andrea Then I would propose to:
> 
> 1. Have a method such as `isWarmUpIteration`, that tells you if something is a warm-up iteration or not.
> 2. Implement it to: in fixed-time policy to return the obvious, in fixed-iterations policy to return true for all iterations but the last.
> 3. If you want constant-time warmup, and one extra measurement iteration (note: fixed-time does constant time warmup and constant time measurement runs), then implement a 3rd policy that does that.

This solution looks good to me.

**Comment by lbulej** [comment]
Support added in #191.
