### ISSUE TITLE
Inclusion of dummy benchmarks in list complicates scripting

### ISSUE THREAD

**Issue by ceresek** [renaissance-benchmarks/renaissance#220]
The `--raw-list` option would be great for scripting the usual "run all benchmarks" task, but it also includes the `dummy` group of benchmarks, which the script has to filter afterwards. Having an option to list the benchmarks without the artificial ones that are not meant for use would be useful.

**Comment by axel22** [comment]
Maybe benchmarks should have a `dummy` status that allows `--raw-list` to filter them out.

**Comment by lbulej** [comment]
We already do some kind of filtering when you specify the `all` group to run all benchmarks -- this excludes benchmarks in the `dummy` group. Since we are already filtering based on the name, we can extend this (group-name-based) filtering to the `--list` and `--raw-list` commands, without adding another benchmark annotation.

So the question is, are we fine with the `dummy` group being special-handled by the harness, or do we want to take it out to the benchmarks and have the harness handle it in generic fashion? I'm somewhat inclined towards the first option, because it seems to me like "harness-internal business" and I would avoid polluting the benchmark parameter namespace with a setting like this.

**Comment by farquet** [comment]
I agree. Let's keep it simple.
