### ISSUE TITLE
CPU_COUNT unused in neo4j-analytics

### ISSUE THREAD

**Issue by lbulej** [renaissance-benchmarks/renaissance#240]
When looking through the setup code of the `neo4j-analytics` benchmark and specifically the `AnalyticsBenchmark.scala` file, I found that the `CPU_COUNT` attribute is set to `Runtime.getRuntime.availableProcessors`, but the value is not used anywhere.

The values of the `LONG_QUERY_NUM`, `SHORT_QUERY_NUM`, and `MUTATOR_QUERY_NUM` attributes come benchmark parameters and are constant (2, 1, and 1, respectively). Do we want to keep them constant, or was there a plan to scale those numbers based on the number of cores?

**Comment by axel22** [comment]
It was probably an oversight to add this field, I'm not aware of any prior plans to make the thread counts variable with the available core count.

Since we already hardcoded the cpu-count in some other (Spark) benchmarks for stability reasons, my suggestion would be to keep the current values as defaults, and (potentially) only implement logic to auto-pick these values if the user sets an option for the parallelism level explicitly.

**Comment by lbulej** [comment]
I'm fine with that. So for now, the resolution is to remove the unused field. If needed, we can create a configuration that will derive those parameters from the number of available CPUs.
