### ISSUE TITLE
Redundant plugin specification breaks the harness

### ISSUE THREAD

**Issue by ceresek** [renaissance-benchmarks/renaissance#391]
It is possible to specify the same plugin twice, once with and once without the main class. When that happens, two plugin instances append to the same result columns, leading to result data with uneven column lengths. This crashes the JSON result writer with `IndexOutOfBounds`:

```
> java -jar renaissance-gpl-0.14.2.jar --plugin plugin-jmxmemory-assembly-0.0.1.jar --plugin plugin-jmxmemory-assembly-0.0.1.jar!org.renaissance.plugins.jmxmemory.Main -r 1 --json /dev/null akka-uct
====== akka-uct (concurrency) [default], iteration 0 started ======
...
====== akka-uct (concurrency) [default], iteration 0 completed (13336.698 ms) ======
[2023-08-18T09:34:06.407+0200] org.renaissance.core (org.renaissance.core.Launcher main)
SEVERE: Harness failed with java.lang.IndexOutOfBoundsException: 1 is out of bounds (min 0, max 0)
	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:99)
	at org.renaissance.harness.JsonWriter.$anonfun$getResultData$5(ResultWriter.scala:392)
	at scala.Option.map(Option.scala:242)
	at org.renaissance.harness.JsonWriter.$anonfun$getResultData$4(ResultWriter.scala:392)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.collection.immutable.List.flatMap(List.scala:79)
	at org.renaissance.harness.JsonWriter.$anonfun$getResultData$3(ResultWriter.scala:392)
	at org.renaissance.harness.JsonWriter.$anonfun$getResultData$3$adapted(ResultWriter.scala:390)
	at scala.collection.immutable.Range.map(Range.scala:59)
	at org.renaissance.harness.JsonWriter.$anonfun$getResultData$2(ResultWriter.scala:390)
	at org.renaissance.harness.JsonWriter.$anonfun$getResultData$2$adapted(ResultWriter.scala:388)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:896)
	at org.renaissance.harness.JsonWriter.getResultData(ResultWriter.scala:388)
	at org.renaissance.harness.JsonWriter.store(ResultWriter.scala:378)
	at org.renaissance.harness.ResultWriter.org$renaissance$harness$ResultWriter$$storeResults(ResultWriter.scala:65)
	at org.renaissance.harness.ResultWriter.beforeHarnessShutdown(ResultWriter.scala:69)
	at org.renaissance.harness.EventDispatcher.notifyBeforeHarnessShutdown(EventDispatcher.java:76)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:186)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:132)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.renaissance.core.Launcher.loadAndInvokeHarnessClass(Launcher.java:129)
	at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:78)
	at org.renaissance.core.Launcher.main(Launcher.java:43)
```

This is a minor issue that only exhibits itself when the user provides a redundant plugin specification, so no biggie. But it does raise some questions:

- Is there ever a need to load the same plugin multiple times ? The `org.renaissance.harness.Config` class seems to assume that this is not the case, and uses a map to store the plugins, but fails to recognize that the two plugin specifications in the example above are in fact the same plugin.

- What exactly is the behavior when a plugin returns a different set of columns on each measurement repetition ?

- Should we guard against conflicts in column names provided by plugins ?

**Comment by lbulej** [comment]
> Is there ever a need to load the same plugin multiple times ? The org.renaissance.harness.Config class seems to assume that this is not the case, and uses a map to store the plugins, but fails to recognize that the two plugin specifications in the example above are in fact the same plugin.

I don't recall this being considered a valid use-case so far, and the contents of the `Config` class reflect it.

If we don't have a use-case, we could try to detect duplicates (e.g., using plugin JAR name and/or main class name) and prevent multiple instantiations with a hard stop, because we do not have clear semantics for multiple instances of the same plugin. Issuing a warning is an option if we want to provide "longer rope" :-)

> What exactly is the behavior when a plugin returns a different set of columns on each measurement repetition ?

Depends on the implementation of the `MeasurementResultListener`, in this case the `ResultWriter` class and its subclasses. At the moment, the `ResultWriter` appends metrics to a buffer found through `Map[BenchmarkName, Map[MetricName, Buffer[Long]]`. This means that if multiple plugins report values with the same name, multiple values will be appended to the buffer, resulting in more values than there are iterations.

The `JsonWriter` and `CsvWriter` classes will dump the metric values for all observed metric names, but because the values are not associated with a particular iteration (they are appended to a buffer sequentially), gaps are not preserved. So far we assumed that every iteration will produce the same set of metrics.

If we have a use-case for that, then `ResultWriter` could be updated to keep track of repetitions and associate values with a particular repetition instead of appending to a buffer sequentially. The CSV and JSON outputs would then contain empty/null values for missing metrics in a particular iteration, preserving gaps. If multiple publishers produce values under the same name, only the last value published under that name will be stored.

We might actually want this semantics regardless of whether we guard against name collisions or not. We could also scream if we find that a value for a particular iteration is already set (without giving specifics as to which plugin provided it). Of course this is not 100% bulletproof, but it could catch some problems.

> Should we guard against conflicts in column names provided by plugins ?

There is no value registration phase in the plugin lifecycle and the `MeasurementResultListener` interface does not identify the source (publisher) of the value.  Consequently, the measurement result listeners have no way of identifying collisions and the name space of metrics is flat from their perspective.

So far, we did not need a bulletproof plugin interface with value registration or name collision detection, because the only known users of the plugin interfaces are those in the repository, i.e., we can choose proper names or add suitable prefixes.

If we want to prevent that, would could extend the `MeasurementResultListener` interface so that the `onMeasurementResult` method includes some sort of a source tag. The listener could then either guard against conflicts or prefix the metric values with the source tag.

The source tag could be either provided by the plugin (meaning we still run the risk of multiple plugins using the same source tag), or by the harness, using some sort of unique identifier (e.g., plugin JAR + main class name, provided we do not allow multiple plugin instances).

I'm thinking that if we implement the first two points (prevent multiple instantiation and raise an error if a value is set twice for a particular iteration), we'll get rid of most potential (unintended) misuses.

**Comment by ceresek** [comment]
I've discovered this issue through a scripting bug, and right now I can't think of any use case for the weirder configurations (multiple instances of the same plugin, multiple values in the same column per repetition, no value in a column for some repetitions).

I believe just implementing an error check for double plugin load would suffice for now (I'd check on main class name, possibly on main class and JAR together, since in some cases we put the plugin classes into the harness bundle).

Prefixing columns with plugin ID would be a straightforward solution (in fact we have such prefix in column names now, inserted manually), but we would have to take care to keep it short, ideally if we did not have to change the column names for the existing plugins. But given the plugins are few, I think we do not have to bother about column name collisions urgently.

On more values or no value per repetition. I think that if we decide to support this use case, we should come up with a mechanism that would completely disconnect repetitions and value provision, but again, right now this is not needed. Plus, some output formats such as CSV would have hard time handling this.

**Comment by lbulej** [comment]
> I believe just implementing an error check for double plugin load would suffice for now (I'd check on main class name, possibly on main class and JAR together, since in some cases we put the plugin classes into the harness bundle).

Will do.

> Prefixing columns with plugin ID would be a straightforward solution (in fact we have such prefix in column names now, inserted manually), but we would have to take care to keep it short, ideally if we did not have to change the column names for the existing plugins. But given the plugins are few, I think we do not have to bother about column name collisions urgently.

I'm perfectly fine with sticking to the manual solution for the time being :-)

> On more values or no value per repetition. I think that if we decide to support this use case, we should come up with a mechanism that would completely disconnect repetitions and value provision, but again, right now this is not needed. Plus, some output formats such as CSV would have hard time handling this.

I would not dare to think of storing multiple values under single name per repetition :-)

However, just modifying `ResultWriter` to keep track of repetitions and setting the metric value for a particular repetition (instead of just appending to a buffer) would provide graceful behavior for the no/missing value case instead of disrupting the order of the values. This should be an easy and cheap fix, if it's something we want.

The simple collision detection has some cost associated, because we would need to keep an extra flag array, or use a `Buffer[java.lang.Long]` (instead of `Buffer[Long]`) which would allow using `null` as a value (at the cost of keeping a number of `Long` objects on the heap, which I believe currently does not happen).

**Comment by ceresek** [comment]
> However, just modifying ResultWriter to keep track of repetitions and setting the metric value for a particular repetition (instead of just appending to a buffer) would provide graceful behavior for the no/missing value case instead of disrupting the order of the values. This should be an easy and cheap fix, if it's something we want

What about just asserting on equal number of values in each column at the end ?
