### ISSUE TITLE
Harness leaves behind temporary files when run on NFS mount

### ISSUE THREAD

**Issue by ceresek** [renaissance-benchmarks/renaissance#464]
Running Renaissance 0.16.0 with the current directory on an NFS mount leaves behind the `launcher` directory:

```
java -jar renaissance-gpl-0.16.0.jar --list
...
ls -R
.:
launcher-101515-11172672929640790059

./launcher-101515-11172672929640790059:
renaissance-harness_3

./launcher-101515-11172672929640790059/renaissance-harness_3:
lib

./launcher-101515-11172672929640790059/renaissance-harness_3/lib:
```

This is not a new issue, the same happened on 0.15.0.

**Comment by lbulej** [comment]
Strange.

The scratch directory deletion code uses a standard-issue `walkFileTree` visitor and has not changed for quite some time (since May 2021, i.e., since release 0.12.0). Also, the two scratch directories (for the launcher and for the harness) are intentionally siblings (in the top-level directory not managed by Renaissance) so that they can be deleted independently.

The only reason why a scratch directory should be left behind is an abrupt exit of the JVM (without running the shutdown hooks) or a delayed disappearance of a deleted file (on NFS) that will ultimately prevent (some) directory from being removed.

I'll check if there are exceptions thrown that would at least shine some light on the cause (there is logging, but I discovered that the `java.util.logging` framework dismantles the loggers in the shutdown hook and will just discard the log messages).

Anyway, even if that is the case, the question is what is the expected behavior when the removal of some file or directory fails in the shutdown hook &mdash; shutdown hook is not exactly a place to wait for file being deleted by the underlying filesystem or for retrying deletion.

**Comment by ceresek** [comment]
After looking at this a bit more - the JAR files in the `lib` directory are apparently still open at the time the cleanup is done, NFS turns them into `.nfs` temporaries to prevent open files from disappearing, subsequently the directory where those files reside cannot be removed, but when the process exits, the `.nfs` temporaries are deleted and thus only the (now) empty directory remains.

**Comment by lbulej** [comment]
I saw such files on NFS before, but was not sure when they are created, but it now becomes clear.

The JAR files are kept open by the `URLClassLoader` instances that we create for the benchmark in the `ModuleLoader`. We need to keep track of them and close the them before trying to delete the scratch directories.

The problem was not visible, even though the shutdown hook was probably printing a warning to `stderr` using `java.util.logging.Logger`, because the logger has been closed already by the `java.util.loggin` shutdown hook. To add an insult to the injury, the dismantling of the logger also closed the `stderr` stream, which is why even printing to `stderr` from the shutdown hook (which I used for testing) sometimes did not display anything. This was caused by using a plain `StreamHandler` (which does not understand `stderr`) in our logging setup code instead of `ConsoleHandler` (which does not close the `stderr` stream on `close()`).
